'use strict';

const STATES = Object.freeze({
  NEW: 'NEW',
  READY: 'READY',
  RUNNING: 'RUNNING',
  WAITING: 'WAITING',
  COMPLETED: 'COMPLETED',
  ABORTED: 'ABORTED',
  FAILED: 'FAILED',
});

const TERMINAL_STATES = Object.freeze(
  new Set([STATES.COMPLETED, STATES.ABORTED, STATES.FAILED])
);

// Legal transitions of the process state machine (PRD section 4.2).
const TRANSITIONS = Object.freeze({
  [STATES.NEW]: [STATES.READY, STATES.ABORTED],
  [STATES.READY]: [STATES.RUNNING, STATES.ABORTED, STATES.FAILED],
  [STATES.RUNNING]: [STATES.COMPLETED, STATES.WAITING, STATES.ABORTED, STATES.FAILED],
  [STATES.WAITING]: [STATES.READY, STATES.ABORTED, STATES.FAILED],
  [STATES.COMPLETED]: [],
  [STATES.ABORTED]: [],
  [STATES.FAILED]: [],
});

const OPERATIONS = Object.freeze({
  UPLOAD: 'UPLOAD',
  EDIT: 'EDIT',
  DELETE: 'DELETE',
  MOVE: 'MOVE',
  DOWNLOAD: 'DOWNLOAD',
  SHARE: 'SHARE',
});

const ALGORITHMS = Object.freeze({
  FCFS: 'FCFS',
  SJF: 'SJF',
  PRIORITY: 'PRIORITY',
});

const LOCK_STATUS = Object.freeze({
  GRANTED: 'GRANTED',
  WAITING: 'WAITING',
});

const EVENT_TYPES = Object.freeze({
  PROCESS_CREATED: 'PROCESS_CREATED',
  STATE_CHANGED: 'STATE_CHANGED',
  ALGORITHM_CHANGED: 'ALGORITHM_CHANGED',
  PROCESS_DISPATCHED: 'PROCESS_DISPATCHED',
  LOCK_GRANTED: 'LOCK_GRANTED',
  LOCK_WAITING: 'LOCK_WAITING',
  LOCK_RELEASED: 'LOCK_RELEASED',
  WAIT_EDGE_ADDED: 'WAIT_EDGE_ADDED',
  DEADLOCK_DETECTED: 'DEADLOCK_DETECTED',
  VICTIM_SELECTED: 'VICTIM_SELECTED',
  ROLLBACK: 'ROLLBACK',
  DEADLOCK_RESOLVED: 'DEADLOCK_RESOLVED',
});

module.exports = {
  STATES,
  TERMINAL_STATES,
  TRANSITIONS,
  OPERATIONS,
  ALGORITHMS,
  LOCK_STATUS,
  EVENT_TYPES,
};
